---
title: "MAPAcrossRace"
output: pdf_document
---

```{r setup, include=FALSE}
#https://www.rdocumentation.org/packages/bigrquery/versions/0.4.1
knitr::opts_chunk$set(echo = TRUE)

library(dslabs)
library(dplyr)
library(tidyverse)
library(bigrquery)
library(readr)
library(httpuv)
library(odbc)
library(sqldf)
library(DBI)
library(comorbidity)
library(tableone)
library(dbplyr)
library(RPostgres)
library(reshape)
library(bayestestR)
library(weathermetrics)
library(ggthemes)
library(pROC)
library(caret)
library(knitr)
library(kableExtra)
library(stringr)
library(rmarkdown)
library(modelsummary)
library(bookdown)
library(scales)
library(glue)
library(extrafont)
library(DiagrammeR)
library(labelled)
library(DescTools)
library(MASS)
library(MLmetrics)

select <- dplyr::select
extrafont::loadfonts(device="win")

options(scipen = 20)

con <- dbConnect(
  bigrquery::bigquery(),
  project = "mimic-gottlieb",
  dataset = "physionet-data.mimiciii_clinical.chartevents",
  )

```

```{sql, connection=con, output.var = "BPs",echo = FALSE}

SELECT patientunitstayid, chartoffset, entryoffset, nibp_systolic, nibp_diastolic, nibp_mean, ibp_systolic, ibp_diastolic, ibp_mean FROM `physionet-data.eicu_crd_derived.pivoted_vital` WHERE chartoffset < 1440 ORDER BY patientunitstayid, chartoffset

```

```{sql, connection=con, output.var = "dialysis",echo = FALSE}

SELECT patientunitstayid, dialysistotal FROM `physionet-data.eicu_crd.intakeoutput` WHERE dialysistotal >0

```

```{r}
#saveRDS(BPs, file = "BPs.rdata")
setwd("C:/Users/egott/OneDrive/Documents/MIT/MAPAcrossRace")
BPs <- readRDS("BPs.rdata")
dialysislist <- unique(dialysis$patientunitstayid)
nondialysisBPs <- BPs %>% filter(!(patientunitstayid %in% dialysislist))
nondialysislistunique <- unique(nondialysisBPs$patientunitstayid)
nondialysislistuniqueSQL <- glue::glue_sql("{nondialysislistunique*}", .con = con2)

nondialysisNIBP <- select(nondialysisBPs, patientunitstayid, chartoffset, entryoffset, nibp_systolic, nibp_diastolic, nibp_mean)
colnames(nondialysisNIBP) <- c("patientunitstayid", "chartoffset", "entryoffset", "SBP", "DBP", "MAP")
nondialysisIBP <- select(nondialysisBPs, patientunitstayid, chartoffset, entryoffset, ibp_systolic, ibp_diastolic, ibp_mean)
colnames(nondialysisIBP) <- c("patientunitstayid", "chartoffset", "entryoffset", "SBP", "DBP", "MAP")

allBPs <- rbind(nondialysisNIBP, nondialysisIBP) %>% arrange(patientunitstayid, chartoffset) %>% group_by(patientunitstayid, chartoffset) %>% summarize(SBP = mean(SBP, na.rm = TRUE), DBP = mean(DBP, na.rm = TRUE), MAP = mean(MAP, na.rm = TRUE)) %>% group_by(patientunitstayid) %>% summarize(SBPauc = area_under_curve(chartoffset, SBP, method = "trapezoid", na.rm = TRUE), DBPauc = Area_Under_Curve(chartoffset, DBP, method = "trapezoid", na.rm = TRUE), MAPauc = area_under_curve(chartoffset, MAP, method = "trapezoid", na.rm = TRUE), starttime = min(chartoffset), endtime = max(chartoffset))

saveRDS(allBPs, file = "allBPs.rdata")

#BPcomplete <- rbind(nondialysisNIBP, nondialysisIBP) %>% arrange(patientunitstayid, chartoffset)

#BPcomplete[MAP < 65, diff(range(chartoffset)), by = patientunitstayid]
```


```{sql, connection=con, output.var = "ICDs",echo = FALSE}

SELECT patientunitstayid, icd9code FROM `physionet-data.eicu_crd.diagnosis`

```

```{r}
saveRDS(ICDs, file = "ICDs.rdata")
ICDs <- readRDS("ICDs.rdata")
Elixhauser <- comorbidity(x = ICDs, id = "patientunitstayid", code = "icd9code", icd = "icd9", score = "elixhauser", assign0 = FALSE)
saveRDS(Elixhauser, file = "Elixhauser.rdata")
Elixhauser <- readRDS("Elixhauser.rdata")
```

```{sql, connection=con, output.var = "demographics",echo = FALSE}

SELECT patientunitstayid, uniquepid, patienthealthsystemstayid, hospitalid, gender, age, ethnicity, apacheadmissiondx, hospitaldischargestatus, unittype FROM `physionet-data.eicu_crd.patient` ORDER BY uniquepid

```

```{r}
saveRDS(demographics, file = "demographics.rdata")
demographics <- readRDS("demographics.rdata")

```

```{sql, connection=con, output.var = "ventilationevents",echo = FALSE}

SELECT patientunitstayid, event, hrs FROM `physionet-data.eicu_crd_derived.ventilation_events`
```

```{r}
saveRDS(ventilationevents, file = "ventilationevents.rdata")
ventilationevents <- readRDS("ventilationevents.rdata")

```

```{sql, connection=con, output.var = "apache",echo = FALSE}

SELECT apachepatientresultsid, patientunitstayid, apachescore, apacheversion FROM `physionet-data.eicu_crd.apachepatientresult`
```

```{r}
saveRDS(apache, file = "apache.rdata")
apache <- readRDS("apache.rdata")

```

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'left'}
labvector <- c("sodium", "potassium","chloride", "bicarbonate", "BUN", "creatinine", "calcium", "magnesium", "phosphorus", "AST (SGOT)", "ALT (SGPT)", "alkaline phos", "total bilirubin", "direct bilirubin", "total protein", "albumin", "WBC x 1000", "Hgb", "platelets x 1000")

labvectorSQL <- glue::glue_sql("{labvector*}", .con = con)
```

```{sql, connection=con, output.var = "labs",echo = FALSE}

SELECT labid, labname, labresult, labresultoffset FROM `physionet-data.eicu_crd.lab` WHERE labname IN (?labvectorSQL) AND labresultoffset <= 1440
```

```{r}
saveRDS(labs, file = "labs.rdata")
labs <- readRDS("labs.rdata")

```

```{r}
allBPs <- readRDS("allBPs.rdata")
Elixhauser <- readRDS("Elixhauser.rdata")
labs <- readRDS("labs.rdata")
apache <- readRDS("apache.rdata")
demographics <- readRDS("demographics.rdata")
ventilationevents <- readRDS("ventilationevents.rdata")

comp <- left_join(allBPs, demographics, by = "patientunitstayid") %>% left_join(Elixhauser, by = "patientunitstayid") %>% left_join(apache, by = "patientunitstayid") %>% filter(!is.na(MAPauc))
```

how frequently blood pressure measured, overall and stratified by race, by hospital
  adjust for age, illness severity, comorbidities
look at biggest hospital in eICU
hypotension as measured by other papers
comorbidities/illness serverity
